// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID             uuid.UUID  `json:"id"`
	UserName       string     `json:"user_name"`
	PasswordHash   string     `json:"password_hash"`
	RegistrationAt *time.Time `json:"registration_at"`
}
