// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const newComment = `-- name: NewComment :exec
INSERT INTO comments 
    (user_id, wall_id, text)
VALUES 
    ($1, $2, $3)
`

type NewCommentParams struct {
	UserID uuid.UUID `json:"user_id"`
	WallID uuid.UUID `json:"wall_id"`
	Text   string    `json:"text"`
}

func (q *Queries) NewComment(ctx context.Context, arg NewCommentParams) error {
	_, err := q.db.Exec(ctx, newComment, arg.UserID, arg.WallID, arg.Text)
	return err
}
