// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
)

const test = `-- name: Test :exec
SELECT id, user_name, password_hash, registration_at FROM users
`

func (q *Queries) Test(ctx context.Context) error {
	_, err := q.db.Exec(ctx, test)
	return err
}
