// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getCommentsByWallID = `-- name: GetCommentsByWallID :many
SELECT id, user_id, wall_id, text, created_at FROM comments WHERE wall_id = $1
`

func (q *Queries) GetCommentsByWallID(ctx context.Context, wallID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getCommentsByWallID, wallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WallID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newComment = `-- name: NewComment :exec
INSERT INTO comments 
    (user_id, wall_id, text)
VALUES 
    ($1, $2, $3)
`

type NewCommentParams struct {
	UserID uuid.UUID `json:"user_id"`
	WallID uuid.UUID `json:"wall_id"`
	Text   string    `json:"text"`
}

func (q *Queries) NewComment(ctx context.Context, arg NewCommentParams) error {
	_, err := q.db.Exec(ctx, newComment, arg.UserID, arg.WallID, arg.Text)
	return err
}
