// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	WallID    uuid.UUID  `json:"wall_id"`
	Text      string     `json:"text"`
	CreatedAt *time.Time `json:"created_at"`
}

type Telegram struct {
	ID             uuid.UUID  `json:"id"`
	TelegramID     int64      `json:"telegram_id"`
	FirstName      string     `json:"first_name"`
	LastName       string     `json:"last_name"`
	Username       string     `json:"username"`
	RegistrationAt *time.Time `json:"registration_at"`
}

type User struct {
	ID               uuid.UUID  `json:"id"`
	UserName         string     `json:"user_name"`
	PasswordHash     string     `json:"password_hash"`
	TelegramRecordID uuid.UUID  `json:"telegram_record_id"`
	RegistrationAt   *time.Time `json:"registration_at"`
}

type Wall struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	CreatedAt *time.Time `json:"created_at"`
}
