// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	WallID    uuid.UUID  `json:"wall_id"`
	Text      string     `json:"text"`
	CreatedAt *time.Time `json:"created_at"`
}

type User struct {
	ID             uuid.UUID  `json:"id"`
	UserName       string     `json:"user_name"`
	PasswordHash   string     `json:"password_hash"`
	RegistrationAt *time.Time `json:"registration_at"`
}

type Wall struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	CreatedAt *time.Time `json:"created_at"`
}
