// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getWallByUserID = `-- name: GetWallByUserID :one
SELECT id, user_id, created_at FROM walls WHERE user_id = $1
`

func (q *Queries) GetWallByUserID(ctx context.Context, userID uuid.UUID) (Wall, error) {
	row := q.db.QueryRow(ctx, getWallByUserID, userID)
	var i Wall
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const setWall = `-- name: SetWall :exec
INSERT INTO walls 
    (user_id)
VALUES 
    ($1)
`

func (q *Queries) SetWall(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setWall, userID)
	return err
}
