// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const newTelegramRecord = `-- name: NewTelegramRecord :one
INSERT INTO telegram
    (telegram_id, first_name, last_name, username) 
VALUES 
    ($1, $2, $3, $4)
RETURNING id
`

type NewTelegramRecordParams struct {
	TelegramID int64  `json:"telegram_id"`
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	Username   string `json:"username"`
}

func (q *Queries) NewTelegramRecord(ctx context.Context, arg NewTelegramRecordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, newTelegramRecord,
		arg.TelegramID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
