// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, telegram_id, first_name, last_name, username, registration_at FROM telegram WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (Telegram, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Telegram
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.RegistrationAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, telegram_id, first_name, last_name, username, registration_at FROM telegram WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (Telegram, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i Telegram
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.RegistrationAt,
	)
	return i, err
}

const newTelegramRecord = `-- name: NewTelegramRecord :one
INSERT INTO telegram
    (telegram_id, first_name, last_name, username) 
VALUES 
    ($1, $2, $3, $4)
RETURNING id, telegram_id, first_name, last_name, username, registration_at
`

type NewTelegramRecordParams struct {
	TelegramID int64  `json:"telegram_id"`
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	Username   string `json:"username"`
}

func (q *Queries) NewTelegramRecord(ctx context.Context, arg NewTelegramRecordParams) (Telegram, error) {
	row := q.db.QueryRow(ctx, newTelegramRecord,
		arg.TelegramID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
	)
	var i Telegram
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.RegistrationAt,
	)
	return i, err
}
