// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_name, password_hash, telegram_record_id, registration_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByUserID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUserID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.TelegramRecordID,
		&i.RegistrationAt,
	)
	return i, err
}

const getUserIDByUserName = `-- name: GetUserIDByUserName :one
SELECT id FROM users WHERE user_name = $1
`

func (q *Queries) GetUserIDByUserName(ctx context.Context, userName string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByUserName, userName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const loginUser = `-- name: LoginUser :one
SELECT id, user_name, password_hash, telegram_record_id, registration_at FROM users WHERE user_name = $1
`

func (q *Queries) LoginUser(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRow(ctx, loginUser, userName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.TelegramRecordID,
		&i.RegistrationAt,
	)
	return i, err
}

const registrationUser = `-- name: RegistrationUser :one
INSERT INTO users
    (user_name, password_hash, telegram_record_id)
VALUES  
    ($1, $2, $3)
RETURNING id, user_name, password_hash, telegram_record_id, registration_at
`

type RegistrationUserParams struct {
	UserName         string    `json:"user_name"`
	PasswordHash     string    `json:"password_hash"`
	TelegramRecordID uuid.UUID `json:"telegram_record_id"`
}

func (q *Queries) RegistrationUser(ctx context.Context, arg RegistrationUserParams) (User, error) {
	row := q.db.QueryRow(ctx, registrationUser, arg.UserName, arg.PasswordHash, arg.TelegramRecordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.TelegramRecordID,
		&i.RegistrationAt,
	)
	return i, err
}

const setNewPasswordByUserID = `-- name: SetNewPasswordByUserID :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetNewPasswordByUserIDParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) SetNewPasswordByUserID(ctx context.Context, arg SetNewPasswordByUserIDParams) error {
	_, err := q.db.Exec(ctx, setNewPasswordByUserID, arg.ID, arg.PasswordHash)
	return err
}

const setNewUserNameUserID = `-- name: SetNewUserNameUserID :exec
UPDATE users SET user_name = $2 WHERE id = $1
`

type SetNewUserNameUserIDParams struct {
	ID       uuid.UUID `json:"id"`
	UserName string    `json:"user_name"`
}

func (q *Queries) SetNewUserNameUserID(ctx context.Context, arg SetNewUserNameUserIDParams) error {
	_, err := q.db.Exec(ctx, setNewUserNameUserID, arg.ID, arg.UserName)
	return err
}
