// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_name, password_hash, registration_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByUserID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUserID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.RegistrationAt,
	)
	return i, err
}

const getUserIDByUserName = `-- name: GetUserIDByUserName :one
SELECT id FROM users WHERE user_name = $1
`

func (q *Queries) GetUserIDByUserName(ctx context.Context, userName string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByUserName, userName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const loginUser = `-- name: LoginUser :one
SELECT id, user_name, password_hash, registration_at FROM users WHERE user_name = $1
`

func (q *Queries) LoginUser(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRow(ctx, loginUser, userName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.RegistrationAt,
	)
	return i, err
}

const registrationUser = `-- name: RegistrationUser :one
INSERT INTO users
    (user_name, password_hash)
VALUES  
    ($1, $2)
RETURNING id, user_name, password_hash, registration_at
`

type RegistrationUserParams struct {
	UserName     string `json:"user_name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) RegistrationUser(ctx context.Context, arg RegistrationUserParams) (User, error) {
	row := q.db.QueryRow(ctx, registrationUser, arg.UserName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.RegistrationAt,
	)
	return i, err
}
